"""Added editote table

Revision ID: 243c05b968dc
Revises: eab05f5e641b
Create Date: 2022-11-22 20:09:23.372190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '243c05b968dc'
down_revision = 'eab05f5e641b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'birthDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthDate', sa.DATE(), nullable=False))
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
