"""Added editote table

Revision ID: 6dc8569bd14b
Revises: 243c05b968dc
Create Date: 2022-11-22 20:09:58.562421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dc8569bd14b'
down_revision = '243c05b968dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userStatus', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
