"""Create models

Revision ID: 6e4764f95b31
Revises: e37af90c621c
Create Date: 2022-11-04 13:01:56.920187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4764f95b31'
down_revision = 'e37af90c621c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('lastName', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.Column('wallet', sa.Float(), nullable=False),
    sa.Column('userStatus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('datePerformed', sa.DateTime(), nullable=False),
    sa.Column('sentByUser', sa.Integer(), nullable=True),
    sa.Column('sentToUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentByUser'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sentToUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('user')
    # ### end Alembic commands ###
