"""Added editote table

Revision ID: eab05f5e641b
Revises: 
Create Date: 2022-11-22 20:07:44.110094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab05f5e641b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('lastName', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.Column('wallet', sa.Float(), nullable=False),
    sa.Column('userStatus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('datePerformed', sa.DateTime(), nullable=False),
    sa.Column('sentByUser', sa.Integer(), nullable=True),
    sa.Column('sentToUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentByUser'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sentToUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('user')
    # ### end Alembic commands ###
